### PR TITLE
Keyword documentation updation

### PR DESCRIPTION
**Pull request by vkosuri**
issue https://github.com/bulkan/robotframework-archivelibrary/issues/16

### CODE REVIEW

**Comment by vkosuri** [comment]
@bulkan do you have any idea on this error?

$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

**Comment by bulkan** [comment]
The error is that there is no Rakefile :P

Why are you trying to run rake ?

**Comment by vkosuri** [comment]
I don't know when i pushed the gh-pages changes Travis started building, then i got this error

**Comment by bulkan** [comment]
Thats weird it doesn't look like Github Pages has changed behavior either https://help.github.com/articles/creating-project-pages-manually/

**Comment by bulkan** [comment]
According to [travis docs](https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches) it shouldnt run on the gh-pages branch, so i'm even more confused

**Comment by vkosuri** [comment]
many we need to turn on **Build only if ```.travis.yml ``` is present** on travis-ci general settings?

build_turnon

**Comment by bulkan** [comment]
I've enabled that option now

**Comment by vkosuri** [comment]
Ha found it is failing due unable to present ```.travis.yml``` wasn't present on gh-pages that's the reason it was failed more information https://github.com/travis-ci/travis-ci/issues/1056

**Comment by vkosuri** [comment]
@bulkan can you make these changes, this is failing due to it doesn't having tests, ArchiveLibaray, could copy all these files into gh-pages?

**Comment by bulkan** [comment]
It doesn't make sense to have tests in the `gh-pages` branch at all. travis should just ignore it

**Pull request closed without merging**
